name: srs
channels:
  - defaults
dependencies:
  - asn1crypto=0.24.0
  - backcall=0.1.0
  - blas=1.0
  - boto=2.49.0
  - boto3=1.8.2
  - botocore=1.11.2
  - bz2file=0.98
  - ca-certificates=2018.03.07
  - certifi=2018.8.24
  - cffi=1.11.5
  - chardet=3.0.4
  - cryptography=2.3.1
  - cycler=0.10.0
  - decorator=4.3.0
  - docutils=0.14
  - freetype=2.9.1
  - gensim=3.4.0
  - idna=2.7
  - intel-openmp=2019.0
  - ipykernel=4.9.0
  - ipython=6.5.0
  - ipython_genutils=0.2.0
  - jedi=0.12.1
  - jmespath=0.9.3
  - jupyter_client=5.2.3
  - jupyter_core=4.4.0
  - kiwisolver=1.0.1
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libpng=1.6.34
  - libsodium=1.0.16
  - llvmlite=0.24.0
  - matplotlib=2.2.3
  - mkl=2019.0
  - mkl_fft=1.0.4
  - mkl_random=1.0.1
  - ncurses=6.1
  - networkx=1.11
  - numba=0.39.0
  - numpy=1.15.1
  - numpy-base=1.15.1
  - openssl=1.0.2p
  - pandas=0.23.4
  - parso=0.3.1
  - pexpect=4.6.0
  - pickleshare=0.7.4
  - pip=10.0.1
  - prompt_toolkit=1.0.15
  - ptyprocess=0.6.0
  - pycparser=2.18
  - pygments=2.2.0
  - pyopenssl=18.0.0
  - pyparsing=2.2.0
  - pysocks=1.6.8
  - python=3.6.6
  - python-dateutil=2.7.3
  - pytz=2018.5
  - pyzmq=17.1.2
  - readline=7.0
  - requests=2.19.1
  - s3transfer=0.1.13
  - scikit-learn=0.19.1
  - scipy=1.1.0
  - setuptools=40.2.0
  - simplegeneric=0.8.1
  - six=1.11.0
  - smart_open=1.6.0
  - sqlite=3.24.0
  - tk=8.6.8
  - tornado=5.1
  - tqdm=4.25.0
  - traitlets=4.3.2
  - urllib3=1.23
  - wcwidth=0.1.7
  - wheel=0.31.1
  - xz=5.2.4
  - zeromq=4.2.5
  - zlib=1.2.11